### ISSUE TITLE
Failed to find a valid digest in the `integrity` attribute

### ISSUE THREAD

**Issue by albilaga** [lxndrblz/anatole#114] opened 2021-01-11 03:07 UTC
Hello. First of all thank you for this beautiful theme. 

I have some issues when I try to deploy the theme to github pages. When I deploy I got error message `Failed to find a valid digest in the 'integrity' attribute for index.html:1 resource 'https://....' with computed SHA256 integrity '.....'. The resource has been blocked.`

Right now I am following this solution https://stackoverflow.com/a/65052963/1351913 and I edited in `themes/anatole/partials/head.html` and remove integrity in there and it is working fine. But maybe if there is another solution for this?

**Comment by lxndrblz** [comment] 2021-01-11 13:12
@albilaga Glad you like the theme. On the site [site](https://albilaga.id/) I can't see an integrity error.

It would be interesting to know, which script caused the error. Do you have a more complete log?

From a security point of view, it's not advisable to remove the integrity check, especially for content hosted on a CDN.

This error reminds me a lot of this issue #64, however, it seemed to be resolved by new. Somehow this issue seems very specific to GitHub Pages, I have never seen it on Netlify or anywhere else.

**Comment by albilaga** [comment] 2021-01-13 06:51
Yes. I don't have error now because I remove the integrity. This is the part where I remove the integrity
```
<!-- CSS -->
    {{ $style := resources.Get "css/style.css" | resources.Minify | resources.Fingerprint }}
    <link rel="stylesheet"
          href="{{ $style.Permalink }}"
          integrity="{{ $style.Data.Integrity }}"
          crossorigin="anonymous"
          type="text/css">
```     
I changed the integrity to `integrity=""` and it is working now. Not sure how to fix if I enable integrity again. And yes I am using github pages

**Comment by gofort** [comment] 2021-01-13 12:50
I have the same issue
You can check it here: https://bogdi.xyz/

**Comment by lxndrblz** [comment] 2021-01-15 16:19
This is an issue commonly reported on other themes too. Basically, would you need to ensure the line endings stay the same. Check out this [documentation](https://help.github.com/en/github/using-git/configuring-git-to-handle-line-endings). Could you please give this a try?

Unfortunately, I can not reproduce the problem on my setup.

**Comment by gofort** [comment] 2021-01-16 10:16
Hmm, I completely remove theme, executed `git config --global core.autocrlf input` and added theme once again and it helped as I see.
Thank you!

**Closed** 2021-01-16 11:22 UTC
Labels: good first issue, question

**Comment by albilaga** [comment] 2021-01-17 02:53
@lxndrblz yes. Looks like that is the issue. Thank you...

**Comment by amaothree** [comment] 2021-04-27 18:06
I have the same issue. And I am using Windows. I try the solution provided by @gofort , executed `git config --global core.autocrlf true` however it not work.
My blog is https://amao.run/en
```
(index):1 Failed to find a valid digest in the 'integrity' attribute for resource 'https://amao.run/css/style.min.7ec96a07e10b60a6997be730fc5d4d3467a225c68515a7df6ae17ac2500f828c.css' with computed SHA-256 integrity '66pWKdY6fEah/OVFT3u1A+0m5T4mufIxbcYCWqycGtg='. The resource has been blocked.
www.googletagmanager.com/gtag/js?id=G-4GTD2DHRN1:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
(index):1 Failed to find a valid digest in the 'integrity' attribute for resource 'https://amao.run/js/medium-zoom.min.2d6fd0be87fa98f0c9b4dc2536b312bbca48757f584f6ea1f394abc9bcc38fbc.js' with computed SHA-256 integrity 'g8sd1f6o1C2H0eYBoH+qcwia0O+cz+Xa9gQSievMTkY='. The resource has been blocked.
```

**Comment by amaothree** [comment] 2021-04-27 18:13
I found this related issue. 
https://github.com/alanorth/hugo-theme-bootstrap4-blog/issues/53

Whatever I will try to use WSL to generate the blog again to check is a Hugo-on-Windows bug.

**Comment by amaothree** [comment] 2021-04-28 20:19
Hi guys. If you are using your own domain name. I think I may have solved this problem.

Make a long story short, turn off Cloudflare's "Always Use HTTPS" function.

I was suffering from this problem for a long time. By checking everyone's solutions, neither my reinstallation of the theme nor changing the git related settings solved the problem.

So, I shifted my focus. I had always suspected that there was a problem with the resource itself, so if it weren't a problem with it, it could be a problem with the browser fetching the resource. Then I thought it might be a problem with HTTPS. So I started checking my settings on Cloudflare, trying to switch some functions on and off. And thus the problem was solved.

**Comment by samuelmay** [comment] 2022-03-26 05:27
Hi all,

I encountered this issue, building on Windows, and deploying to GitHub pages. The site displayed fine with the Hugo server locally, but would break with this error when published and viewed on github.io.

I believe it's due to the CR/LF line endings on Windows causing the checksums to be different. Specifically for me, I narrowed it down to the fontawesome css files in "assets\fontawesome\css\".

If you are encountering this issue, I would suggest editing the 3 files in this directory, and using EOL conversion in your text editor to convert them all to Unix LF endings. Then republish.

As an upstream fix I might suggest that something like `*.min.css text eol=lf` to the .gitattributes file for this theme? I'll experiment a bit and fork/pull request when I get a chance.

**Comment by p0n1** [comment] 2023-08-24 15:57
If you deployed hugo generated website with cloudflare, you may encounter CSS or JS integrity issues.

Found this solution. Works for me. https://stackoverflow.com/questions/65040931/hugo-failed-to-find-a-valid-digest-in-the-integrity-attribute-for-resource

Try to turn off Auto Minify feature for CSS or JS because cloudflare may change your CSS or JS files.

As they documented.

> Note: Please note that this feature may not be fully compatible with certain newer CSS and JS language features, which could potentially affect the functionality of your site.
