### ISSUE TITLE
Emoji Colors on Headers

### ISSUE THREAD

**Issue by a0m0rajab** [lxndrblz/anatole#270] opened 2021-12-11 18:56 UTC
**Describe the bug**

The emojis usually come with their own colors yet when using them in the theme it gets black if it's in the header or the title.

**To Reproduce**

Just use an emoji in the header texts or titles. 

**Expected behavior**

to have the same color of the emoji.

**Screenshots**

https://a0m0rajab.github.io/

I think there is a CSS tag that is changing the emoji color but could not find the solution for it yet.

**Comment by lxndrblz** [comment] 2021-12-11 19:17
Hi there,

The emojis are controlled by your operating system and not by theme. Your website for example looks fine on Android, while Microsoft might use different emojis.

![Screenshot_2021-12-11-20-14-25-649_com.android.chrome.jpg](https://user-images.githubusercontent.com/12200062/145688810-51b3668f-80d7-48f1-a0db-1d58d39acffb.jpg)

Unfortunately, this behavior is not controlled by the theme and as far as I know can't be changed.

Going to close this issue as it's not caused by theme. Feel free to let me know if you need additional insights.

**Closed** 2021-12-11 19:24 UTC
Labels: invalid
