### ISSUE TITLE
Disqus comments not working

### ISSUE THREAD

**Issue by adamj-codethink** [lxndrblz/anatole#3] opened 2020-05-04 21:57 UTC
hi,

I have also enabled comments in my posts and set my disqusShortname, but none of the posts contain any disqus links?

Any idea what this could be?

thanks

**Comment by lxndrblz** [comment] 2020-05-05 05:37
Hi Adam,

Thanks for helping to make this theme better.

I've just verified your issue on my personal site. Unfortunately, I couldn't reproduce the issue there, but never the less I want to help you in addressing the issue on your site too.

Did you make sure to uncomment the disqus section in the `config.toml`?

Before:

```
# Enable Disqus
#disqusShortname = ""
```

After:
```
# Enable Disqus
disqusShortname = "mydisquscode-com"
```

Something else that should be noted is that Disqus doesn't load locally and it's only applied to pages of type `post`.

Please let me know if either of the two answers helped you in resolving your issue.

Alex

**Comment by adamj-codethink** [comment] 2020-05-05 07:46
Hey Alex,

No problem, i really like this theme so would love to get everything working :)

This is also my first Hugo blog, so i could be making silly mistakes (sorry).

So my Disqus config is set exactly like that.

However as you stated i did not realise Hugo had a "type" setting for "posts" as i assumed if it was unders the posts directory that it would be parsed as such.

Adding `type: posts` fixed this!

I don't think any of the example posts under the "exampleSite" directory show an example of setting `type: "page"`, maybe that would help if others find this issue in the future.

Thanks for your help again :)

**Closed** 2020-05-05 07:48 UTC
Labels: help wanted
