### ISSUE TITLE
Error in build after theme update

### ISSUE THREAD

**Issue by mattarnster** [lxndrblz/anatole#91] opened 2020-11-23 20:55 UTC
I get the following after I tried to update the theme:
```
PS F:\workspace\web\mattarnster.co.uk> hugo serve
Start building sites … 
ERROR 2020/11/23 15:53:25 render of "taxonomy" failed: execute of template failed: template: _default/list.html:3:4: executing "_default/list.html" at <partial "head.html" .>: error calling partial: "F:\workspace\web\mattarnster.co.uk\themes\anatole\layouts\partials\head.html:22:33": execute of template failed: template: partials/head.html:22:33: executing "partials/head.html" at <fingerprint>: error calling fingerprint: <nil> can not be transformed
ERROR 2020/11/23 15:53:25 render of "page" failed: execute of template failed: template: _default/single.html:3:4: executing "_default/single.html" at <partial "head.html" .>: error calling partial: "F:\workspace\web\mattarnster.co.uk\themes\anatole\layouts\partials\head.html:22:33": execute of template failed: template: partials/head.html:22:33: executing "partials/head.html" at <fingerprint>: error calling fingerprint: <nil> can not be transformed
ERROR 2020/11/23 15:53:25 render of "taxonomy" failed: execute of template failed: template: _default/list.html:3:4: executing "_default/list.html" at <partial "head.html" .>: error calling partial: "F:\workspace\web\mattarnster.co.uk\themes\anatole\layouts\partials\head.html:22:33": execute of template failed: template: partials/head.html:22:33: executing "partials/head.html" at <fingerprint>: error calling fingerprint: <nil> can not be transformed
ERROR 2020/11/23 15:53:25 render of "term" failed: execute of template failed: template: _default/list.html:3:4: executing "_default/list.html" at <partial "head.html" .>: error calling partial: "F:\workspace\web\mattarnster.co.uk\themes\anatole\layouts\partials\head.html:22:33": execute of 
template failed: template: partials/head.html:22:33: executing "partials/head.html" at <fingerprint>: error calling fingerprint: <nil> can not be 
transformed
Built in 31 ms
Error: Error building site: failed to render pages: render of "section" failed: execute of template failed: template: _default/list.html:3:4: executing "_default/list.html" at <partial "head.html" .>: error calling partial: "F:\workspace\web\mattarnster.co.uk\themes\anatole\layouts\partials\head.html:22:33": execute of template failed: template: partials/head.html:22:33: executing "partials/head.html" at <fingerprint>: error calling fingerprint: <nil> can not be transformed
```

Can you see what's going wrong at all? I did the update the recommended way, as defined within the readme for the theme.

**Comment by mattarnster** [comment] 2020-11-23 21:04
Found the issue... It wasn't liking my customCSS[] decleration in config.toml.

I had:
```

**Comment by lxndrblz** [comment] 2020-11-23 21:10
I've just cloned your repository and have been able to reproduce the error. I'll have a look. Possibly it's even related to the other open issue, that we have. #64

**Comment by lxndrblz** [comment] 2020-11-23 21:33
@mattarnster  Your custom css now goes in the assets/css directory and no longer in the static/css directory. This was caused by a change how the Hugo gets these resources.

As a little heads up: Since the recent updates the font awesome prefixes have changed. In your config.toml, you'll have to prefix them now like this: 
```
[[params.socialIcons]]
icon = "fab fa-github"
title = "GitHub"
url = "https://github.com/mattarnster"

[[params.socialIcons]]
icon = "fab fa-twitter"
title = "Twitter"
url = "https://twitter.com/mattarnster"

[[params.socialIcons]]
icon = "fas fa-envelope"
title = "Email"
url = "mailto:matt@mattarnster.co.uk"
```

**Comment by mattarnster** [comment] 2020-11-23 21:50
Awesome, thanks for looking into that for me.

Much appreciated!

**Comment by lxndrblz** [comment] 2020-11-23 21:58
@mattarnster  No problem. I'll go ahead and close this issue. Feel free to reopen it if you have any further issues.

**Closed by lxndrblz** 2020-11-23 21:58 UTC
Labels: help wanted
